language: haskell
before_install:
    # Uncomment whenever hackage is down.
    #- mkdir -p ~/.cabal && cp config ~/.cabal/config && cabal update

install:
    - cabal install test-framework test-framework-hunit
    - cabal configure $mode
    - cabal build

script:
    - $script

notifications:
    email: true

env:
    - mode="--enable-tests" script="cabal test"
